---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.78, CPAN::Meta::Converter version 2.132661'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Crypt-RandPasswd
no_index:
  directory:
    - t
    - inc
resources:
  repository: git://github.com/neilbowers/Crypt-RandPasswd.git
version: 0.04
